easylistgermany/easylistgermany_specific_block.txt
Added honor 8 black friday image http://stadt-bremerhaven.de/wp-content/uploads/2016/11/h8bf.jpg
=> A: http://stadt-bremerhaven.de/

easylistgermany/easylistgermany_specific_block.txt
Not sure if this repo is the correct way to contribute to the easylist germany list.
If not, please redirect me to the correct place :)
=> Add new 4players rule

easylistgermany/easylistgermany_specific_block.txt
They are quick :)
I don't what I should edited in the first line, hope it's okay for you.
=> Add 4players rule

easylistgermany/easylistgermany_specific_hide.txt
https://forums.lanik.us/viewtopic.php?f=90&t=37659
=> A: https://metager.de/meta/meta.ger3?eingabe=ebike

easylistgermany/easylistgermany_adservers.txt
```
http://s.altrk.net/g/py138st
http://s.altrk.net/g/c87ubdp
http://s.altrk.net/g/zjsuvbm
http://s.altrk.net/g/klktr90
```
=> A: https://www.smarthomearea.de/

easylistgermany/easylistgermany_thirdparty_popup.txt
https://forums.lanik.us/viewtopic.php?p=145682#p145682
=> A: http://movie-blog.cc/

easylistgermany/easylistgermany_adservers.txt
https://forums.lanik.us/viewtopic.php?f=62&t=42651
=> A: https://www.volksstimme.de/

easylistgermany/easylistgermany_specific_hide.txt
https://forums.lanik.us/viewtopic.php?f=90&t=42938
=> A: https://www.billiger-telefonieren.de/mobiles-internet-vergleich/ergebnis/

easylistgermany/easylistgermany_specific_hide.txt
https://imgur.com/7frb0gs.png
https://forums.lanik.us/viewtopic.php?p=147664#p147664
=> A: https://www.spiegel.de/schlagzeilen/

easylistgermany/easylistgermany_general_hide.txt
https://forums.lanik.us/viewtopic.php?f=62&t=43263
=> A: https://www.woz.ch/1928/

easylistgermany/easylistgermany_specific_hide.txt
https://forums.lanik.us/viewtopic.php?p=148700#p148700
=> A: https://www.welt.de/wirtschaft/article196683317/I.html

easylistgermany/easylistgermany_adservers.txt
=> A: https://www.pietsmiet.de/videos/55873

easylistgermany/easylistgermany_adservers.txt
see #52 for reference; this is their secondary domain
=> A: threepi.de

easylistgermany/easylistgermany_whitelist.txt
https://forums.lanik.us/viewtopic.php?f=90&t=43709
=> M: (radio.de) removed obsolete whitelist 75f8125

easylistgermany/easylistgermany_specific_block.txt
https://forums.lanik.us/viewtopic.php?p=150810#p150810
=> A: http://highway-magazin.de/

easylistgermany/easylistgermany_specific_hide.txt
https://forums.lanik.us/viewtopic.php?f=90&t=43778
=> A: https://www.saechsische.de/

easylistgermany/easylistgermany_specific_hide.txt
https://forums.lanik.us/viewtopic.php?p=151722#p151722
=> A: https://www.hanf-magazin.com/

easylistgermany/easylistgermany_specific_hide.txt
https://forums.lanik.us/viewtopic.php?p=151721#p151721
=> A: https://www.spiegel.de/stil/think-a-1299788.html

easylistgermany/easylistgermany_specific_hide.txt
https://github.com/easylist/easylist/pull/4425
=> A: A: http://greenbyte.ch/

easylistgermany/easylistgermany_specific_hide.txt
saechsische.de changed their markup
=> update for saechsische.de

easylistgermany/easylistgermany_specific_hide.txt
Hide left-over ad containers.
Site to test, (free) login required: https://www.nzz.ch/technologie/mein-neues-digitales-leben-in-china-ld.1648916
=> A: https://www.nzz.ch/

easylistgermany/easylistgermany_adservers.txt
Block adserver responsible for banners at https://www.yabeat.io/
Screenshots:
=> A: https://www.yabeat.io/

easylistgermany/easylistgermany_specific_hide.txt
updated the rules to fit to the changed saechsische.de website
=> Upate rules for saechsische.de

easylistgermany/easylistgermany_specific_block_popup.txt
Block redirects at https://kinoonline.su/
Screenshot:
=> A: https://kinoonline.su/

easylistgermany/easylistgermany_specific_hide.txt
Hide ad in the middle of articles, e.g. https://medienwoche.ch/2020/01/28/private-wollen-streamingplattform-mit-srg/
=> A: https://medienwoche.ch/

easylistgermany/easylistgermany_specific_hide.txt
Hide overlay at kinomax.to
**Adserver added to EL -** `https://ducina.com/script/suv4r.js`
Screenshot:
=> A: https://kinomax.to/

easylistgermany/easylistgermany_specific_hide.txt
=> A: https://nachbelichtet.com/

easylistgermany/easylistgermany_specific_block_popup.txt
Image popups + popup messages at https://aniworld.to/
Screenshots:
=> A: https://aniworld.to/

easylistgermany/easylistgermany_allowlist.txt
=> F: Unhide in-content video on caravaning.de

easylistgermany/easylistgermany_specific_hide.txt
=> A: Ads on Fazemag.de

easylistgermany/easylistgermany_allowlist.txt
Missing content on musikexpress.de
=> F: Content blocked on www.musikexpress.de

easylistgermany/easylistgermany_specific_hide.txt
Fix OCH download buttons and hide ad content before it
=> M: https://ddl-warez.cc/

easylistgermany/easylistgermany_specific_hide.txt
=> A: https://www.traktorpool.de/

easylistgermany/easylistgermany_specific_hide.txt
Hide ads.
Sites to test:
- https://www.woz.ch
- https://www.woz.ch/2240/solaroffensive/solaroffensive-in-irrem-tempo-an-der-verfassung-vorbei/%21ACT6SZAHTY2H
=> A: https://www.woz.ch

easylistgermany/easylistgermany_allowlist.txt, easylistgermany/easylistgermany_allowlist_general_hide.txt
Fix content being blocked at: 
https://www.stern.de/panorama/ramsan-kadyrow-haut-auf-louis-vuitton-boxsack---den-karl-lagerfeld-kreierte-32788984.html
Screenshot:
=> P: https://www.stern.de/

easylistgermany/easylistgermany_specific_hide.txt
Hide banners all over the page + text placeholders.
If decided to keep the text : `froheweihnachten.info,weihnachten.me,weihnachts-bilder.org,weihnachts-filme.com##div > img[referrerpolicy="unsafe-url"]`
=> A: https://www.weihnachten.me/

easylistgermany/easylistgermany_specific_hide.txt
Please review and add this specific filter as there are ads on the top of the page on mobile version. 
Thank you
=> A: `https://www.n-tv.de/`

easylistgermany/easylistgermany_allowlist_general_hide.txt
Please add this allowlisting filters.
Actual page content its being hidden. 
Thank you
=> F: (missing content on `eltern.de`)

easylistgermany/easylistgermany_allowlist.txt
Please add these filters and the domain to the existing one's it blocks the video content
=> F: (blocks video content) `rollingstone.de`

easylistgermany/easylistgermany_specific_hide.txt
Hide leftover ad title
Site to test: https://www.falter.at/zeitung/20230118/gelesen-buecher--kurz-besprochen/_04d1d3d009
=> A: https://www.falter.at

easylistgermany/easylistgermany_specific_hide.txt
Fix download buttons
Site to test: https://ddl-warez.cc/video/serien/how-to-sell-drugs-online-fast-2019-s01-s03-complete-german-dl-2160p-webrip-x265-ctfoh/
=> M: https://ddl-warez.cc

easylistgermany/easylistgermany_specific_hide.txt
Banners at https://celler-presse.de/2023/01/31/mehr-arbeitslosigkeit-im-winter-robuste-arbeitskraeftenachfrage/
=> A: https://celler-presse.de/

easylistgermany/easylistgermany_specific_hide.txt
Fix broken layout at https://www.jetzt.de/
Screenshot:
=> A: https://www.jetzt.de/

easylistgermany/easylistgermany_specific_hide.txt
Use broader selector to hide ad banners (now also hides leftover ad container on landing page https://www.woz.ch/).
=> M: https://www.woz.ch/

easylistgermany/easylistgermany_specific_hide.txt
Hide leftover ad container.
Site to test: https://weltwoche.ch/
=> A: https://weltwoche.ch/

easylistgermany/easylistgermany_allowlist_general_hide.txt
=> A: https://www.handelsblatt.com/

easylistgermany/easylistgermany_specific_block.txt, easylistgermany/easylistgermany_specific_hide.txt
Hi please review this domain for example on this [page ](https://www.quoka.de/automarkt/winterreifen/sc_82.html) there are lazy loading banners:
And there is also an leftover empty space at the top of the page:
=> A:`quoka.de`

easylistgermany/easylistgermany_specific_hide.txt
A: https://www.otto.de/suche/fernseher
=> A: https://www.otto.de/suche/fernseher

easylistgermany/easylistgermany_specific_hide.txt
Empty placeholders on the page on mobile version: 
Thank you
=> A:`buzzfeed.de`

easylistgermany/easylistgermany_specific_hide.txt
Hi could you please add this to the list there are  couple of google ads on mobile marked with this class:
thank you
=> A:`wetter.com`

easylistgermany/easylistgermany_specific_hide.txt
Empty placeholders on the page in mobile view:
=> A:`rtl.de`

easylistgermany/easylistgermany_specific_hide.txt
Hi please add the domain to the existing filter there is a retail media widget at the bottom of the page:
Thank you
=> A:`abenteuerfreundschaft.de`

easylistgermany/easylistgermany_specific_hide.txt
Ads on the right side of the page:
For example on this article: `https://www.tollabea.de/kindersprueche-zum-schlapplachen-kindermund-421/`
=> A:`tollabea.de`

easylistgermany/easylistgermany_specific_hide.txt
Hi please check out this domain at the bottom of the page there is an advertisement 
Thank you
=> A:`glycerinwissen.de`

easylistgermany/easylistgermany_specific_hide.txt
Advertising banner embedded in the content on this page `https://hallobuer.ruhr/verdacht-der-hehlerei-polizei-stellt-drei-fahrraeder-sicher/`
Thank you
=> A:`hallobuer.ruhr`

easylistgermany/easylistgermany_specific_hide.txt
Hide sponsored content (native ads).
Site to test: https://www.nzz.ch/
=> M: https://www.nzz.ch/

easylistgermany/easylistgermany_specific_hide.txt
Hi could you please add this filter to the list there is a video ad on the page:
Thank you
=> A:`infoheute.de`

easylistgermany/easylistgermany_specific_hide.txt
Hi, there are some ads on top of the [page ](https://www.celleheute.de/politik )and on the bottom 
Thank you
=> A:`celleheute.de`

easylistgermany/easylistgermany_allowlist_general_hide.txt
Broken layout at https://www.kombi.de/
=> A: https://www.kombi.de/

easylistgermany/easylistgermany_specific_hide.txt
Hi there are a couple of 3-rd part banners on the main page:
Thanks you
=> A:`motorradundreisen.de`

easylistgermany/easylistgermany_specific_hide.txt
Ads on the right side of the page:
Thank you
=> A:`parfumo.de`

easylistgermany/easylistgermany_specific_hide.txt
Ads on the main page embedded on the page:
Thanks you
=> A:`rockantenne.hamburg`

easylistgermany/easylistgermany_specific_hide.txt
Ads on the right side of the page:
best regards,
=> A:`bbqpit.de`

easylistgermany/easylistgermany_specific_hide.txt
Affiliate  3rd party ads widgets:
=> A:`veggies.de`

easylistgermany/easylistgermany_specific_hide.txt
Site to test: https://www.persoenlich.com/medien/neuer-leiter-fur-automated-journalism-projekt
=> A: https://www.persoenlich.com/

easylistgermany/easylistgermany_specific_hide.txt
Site to test: https://gastrojournal.ch/home/gastronomie/coca-cola-stellt-nachhaltigkeit-und-zuckerfrei-in-den-fokus
=> A: https://gastrojournal.ch/

easylistgermany/easylistgermany_allowlist.txt
Overblocking self-promo content (podcast in this case)
=> A: manager-magazin.de

easylistgermany/easylistgermany_specific_hide.txt
=> P: (breaking navigation) https://www.home24.de
